### ISSUE TITLE
Features required

### ISSUE THREAD

**Issue by darryllane** [vesche/basicRAT#11]
Hiya I was looking to do something similar, I'm keen to help out. Do you have anything that requires doing? Maybe add a 'todo' list can PPS can work on functionality?

**Comment by darryllane** [comment]
Also recommend subprocess over OS.system, better exception handling it takes parametised arguments to so safer amongst other things

**Comment by vesche** [comment]
Hi @darryllane , there's a todo within the README. Also, `os.system` isn't used anywhere in the project. We do use `subprocess` for command execution already, see line 48 in `basicRAT_client.py`.
