### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by mcb180** [vesche/basicRAT#13]
Hi,
I love your idea, execution, and everything! This seems like a fascinating project and I was hoping to learn from it myself, unfortunately all of the computers i try this on, the program errors out while trying to import the modules. This could just be me missing something obvious, or a real issue, probably the first one, but I wanted to point this out in case it would help someone.

**Comment by deadPix3l** [comment]
I am unaware of any import errors, but it is possible. while i look into it, could you please post the errors you are getting?

**Comment by vesche** [comment]
Make sure you are downloading the entire source code for basicRAT, make sure you have the core/ folder with all contents. I'm going to close this as it is not an issue, but feel free to reply and we can help you out.
