### ISSUE TITLE
lag in response cause reply to appear in the wrong command

### ISSUE THREAD

**Issue by Krysher** [vesche/basicRAT#16]
If client is on a slower machine or connection and you attempts to do let's say 
`execute dir` that takes a bit of time to execute
the client will be lock up for a bit, the server gets no response and just goes on as always, there is no thread that prints out RecvGCM results as we receive it (and that wouldn't be a good idea anyway), only when you type in a command that it print it out what the result is.

So some time, you would do 'execute dir' then 'execute whoami' you would get 'execute dir' result instead.
This get more complicate as download and upload, which could corrupt your file. 

Not sure if this is caused by my modification but as far as encryption and send/recvGCM goes, it is untouched.

**Comment by deadPix3l** [comment]
this is a known issue and a difficult one to address. Yes, if you intentionally run a command that takes too long, it will force the results to buffer until the next command is sent.

the problem with fixing it is the multiclient aspect. hanging and waiting, possibly for a while, is not ideal if you would like to interact with other victims. blurting the answer out whenever it's available is also a terrible idea. the ideal solution has yet to be found. I have tried patching this and am open to suggestions.

**Comment by Krysher** [comment]
We could assign a sequence number for command and response? And some sort of time out global variable if we don't hear back from this sequence execute dir #42, with a respond with seq #42 after 10 seconds - ignore it we will move on.

**Comment by deadPix3l** [comment]
by ignore and move on do you mean throw away the result? it would certainly fix the buffering issue, but it would limit the commands you could run to those that can be completed in 10 seconds. If your victim is using a slow connection on the other side of the planet, this could even disqualify a simple 'ls' from returning

**Comment by Krysher** [comment]
Maybe do some sort of average in respond time and adjust the time out?

**Comment by Krysher** [comment]
Actually, I got a pretty clever hotfix. Add a function that clear out the response buffer. So before any intensive query like upload/download, we can just clear it out or if along the way the buffer get messed up, we can clear that out.

**Comment by kodeine** [comment]
how about using queues for commands jobs?

**Comment by vesche** [comment]
This should now be fixed with the refactor. More here: https://github.com/vesche/basicRAT/pull/21
