### ISSUE TITLE
reconnect

### ISSUE THREAD

**Issue by kodeine** [vesche/basicRAT#18]
if a server is disconnected and re-connected, client wont reconnect.

**Comment by vesche** [comment]
Yes, currently the RAT does not have a re-connection feature. I will keep this open until it is implemented as it has been discussed and will be added in the near future.

**Comment by vesche** [comment]
This has now been fixed. https://github.com/vesche/basicRAT/commit/013a6a06bb1e5e9afdb8abff0395659c3ef236d6
