### ISSUE TITLE
Fatal Error, Failed to execute script basicRAT_client

### ISSUE THREAD

**Issue by cyankw** [vesche/basicRAT#19]
Platform: windows10
My situation:
I checked the SHA-1 of [basicRAT_client.py] between the one I use and the original one, it's the same.
And the argument I give to Pyinstaller is: [ -F -w] as you mentioned in the readme file.

Problem:
My basicRAT_client.exe seems only will work on local, when the sever script is running.
When the basicRAT_client.exe works on other PC or when the sever hadn't been start, it will jump a window like this:
![0](https://cloud.githubusercontent.com/assets/13176405/25772906/03465120-32a7-11e7-913f-b2e9f66141f8.png)
Yet, while I run the exe file on my local PC and with the sever.py running, all the function are able to use.

I don't quiet understand why this happened
Could you plz have a look at this?
@vesche

**Comment by deadPix3l** [comment]
try this:
https://github.com/pyinstaller/pyinstaller/issues/2015
