### ISSUE TITLE
a NOT URGENT command execute delay

### ISSUE THREAD

**Issue by cyankw** [vesche/basicRAT#23]
you make the EXECUTE function A LOT better than it was before. It's was really GREAT.
Much more stable and also less delay.

Yet, the delay of command execute still happens sometimes, it won't cause any other effects except the delay. 
this might not even need to be fixed, just for reminding.

-----------------error output------------------
[1] basicRAT> pwd
Running pwd...
C:\Users\0\Desktop\PYN\basicRAT-master

pwd completed.

[1] basicRAT> ls VER
Running ls...
C:\Users\0\Desktop\PYN\basicRAT-master

**Comment by vesche** [comment]
This should be fixed now: https://github.com/vesche/basicRAT/commit/e4d241ff43192223af3acd4985b4d4ac537596c1
