### ISSUE TITLE
replace dict2json for clarity

### ISSUE THREAD

**Issue by deadPix3l** [vesche/basicRAT#32]
instead of
```
def dict2json(d):
    return json.dumps(d)
```
which adds unneeded obfuscation, i suggest `from json import dumps as dict2json` or similar
may submit pull later - this issue is mostly for reference, or if you want to fix before i get to it.

**Comment by vesche** [comment]
I agree. Fixed, [here](https://github.com/vesche/basicRAT/commit/2bfec923a15f59510aa948c74b6810239fffe1ea).
