### ISSUE TITLE
Build client does not work on Kali 2016.2 64 bit solution included 

### ISSUE THREAD

**Issue by HudsonSeiler** [vesche/basicRAT#4]
[https://www.offensive-security.com/kali-linux-vmware-virtualbox-image-download/](url)
On Kali Linux VirtualBox
Kali Linux Light 64 bit VBox	Torrent	1.2G	2016.2	DB154D8331356361281AB665F0B3AA09D2B380F3

[https://www.kali.org/news/kali-linux-metapackages/](url)
With Kali Linux Metapackages 
kali-linux-all 
Installation Size: 15 GB

Do not use           `root@kali:~/basicRAT#pyinstaller2 --onefile basicRAT_client.py`
use the following `root@kali:~/basicRAT# pyinstaller --onefile basicRAT_client.py`

Tested as of 02-06-17

**Comment by vesche** [comment]
What the PyInstaller binary is named is going to depend on your Linux distribution. I built it on Arch Linux where the PyInstaller binary in the [AUR](https://aur.archlinux.org/packages/pyinstaller2/) is called `pyinstaller2`. However, I bet on most Linux distributions this binary will be named just `pyinstaller`. I'm planning on making a binary generation script later, so I'll incorporate this then. For now I'm going to close this issue as it's pretty minor. Thanks.

**Comment by kodeine** [comment]
`pyinstaller --onefile basicRAT_client.py` does not run on macos ? am i missing something?

**Comment by vesche** [comment]
If you created a stand alone executable with PyInstaller on Linux it will not run on macOS. You will need to download PyInstaller on macOS and then build a Mach-O executable.
