### ISSUE TITLE
Make encryption suck less and provide security/integrity/authenticity guarantees

### ISSUE THREAD

**Issue by HarryR** [vesche/basicRAT#5]
Hai.

I hacked together a quick example of how, instead of using PyCrypto, the PyNaCl library can be used to provide a less sucky encryption layer with modern security guarantees.

 See: https://gist.github.com/HarryR/5420bac1025250b3a218a8e327d8a3e6

 This allows the client to verify the integrity of the server its talking to, you must hard-code the servers long-term public-key into the client, however the server doesn't need to know the long-term public key of the client.

 An ephemeral key is created by either side for each connection, then a shared secret is negotiated between the two sides. This provides forward-secrecy in the event that a passive listener obtains either sides long-term secret keys.

The code could be simplified and made a little more readable by using `str(key)` instead of `key.encode(encoder=RawEncoder)`... Aside from that it's very clean, but could do with a second pair of eyes.

**Comment by vesche** [comment]
We are in the process of incorporating 256-bit AES GCM using [this implementation](https://github.com/bozhu/AES-GCM-Python). Thanks for the dialogue however, and I hope this makes our encryption suck less.

**Comment by vesche** [comment]
FYI 256-bit AES GCM was implemented in this commit: https://github.com/vesche/basicRAT/commit/95394f3da2634143a66b246f45f0afb0e4926159

**Comment by HarryR** [comment]
Ah cool, but there's still no authentication of either side, meaning the DH exchange provides forward secrecy, but you're unsure if you're talking to the right C2...

**Comment by vesche** [comment]
The [GCM implementation](https://github.com/bozhu/AES-GCM-Python) we are using has GMAC, an authentication-only variant of the GCM which can be used as an incremental message authentication code.

**Comment by HarryR** [comment]
It verifies that the data you've sent is the same as is received, but it doesn't verify that the other party is the one you want to talk to.

At the moment it looks like it provides forward secrecy via the initial DH exchange, and transmission integrity+secrecy via AES-GCM.

**Comment by deadPix3l** [comment]
Your observations are noted and correct. there is no validation of C2 servers, and it is very possible that the clients will connect to intercepting attackers. but we are not concerned greatly about fixing this. adding validation like public key or challenge response protocols would greatly complicate this project, which is still in its infancy. As a hacking tool (act responsibly), we are not greatly concerned about other hackers at this point in time, but your concern is appreciated.
