### ISSUE TITLE
devel - several fixes

### ISSUE THREAD

**Issue by deadPix3l** [vesche/basicRAT#7]
[this issue is here to document my struggles, and to provide a tracker for my progress]

- gcm support is minimal. reimplement all other commands.
- figure out diffie hellman error where rekey results in different keys
- make rekey actually do something in the new system (the new DH key is never used)
- trackdown error where the commands output is delayed one cycle
- create client class to hold all variables, and to clean up the code. May integrate/be replaced by multiclient support

**Comment by vesche** [comment]
Most of this is fixed now, I made the rekey problems into a separate issue tracker. Fixing rekey and file upload/download will be a priority.
