### ISSUE TITLE
Crash when transmitted data size exceeds buffer

### ISSUE THREAD

**Issue by reznok** [vesche/basicRAT#8]
`        # results of a command`
        `elif cmd == 'run':`
            `recv_data = self.conn.recv(4096)`
            `print crypto.AES_decrypt(recv_data, self.dh_key).rstrip()`

If the data size exceeds 4096, it will crash the server as well as all connected clients.
I've drafted up a fix (that was actually in my multi-client PR) that sends the data size as the first 4 bytes so the server knows how much data it needs to receive. 

example:
Sending:
   ` enc_message = crypto.AES_encrypt(message, dh_key)`
    `sock.send(struct.pack('>I', len(enc_message)) + enc_message)`

Receiving:
    `msglen = struct.unpack('>I', s.recv(4))[0]` 
    `data = crypto.AES_decrypt(s.recv(msglen), dh_key)`

I believe the filesock uses something similar.
This would be a good solution unless an extremely large amount of data is being sent.

**Comment by vesche** [comment]
Could you post the traceback you are getting when this happens?

**Comment by reznok** [comment]
[?] basicRAT> clients
ID - Client Address
 1 - 127.0.0.1

[?] basicRAT> client 1
Client 1 selected.

[1] basicRAT> run cat /etc/passwd
Traceback (most recent call last):
  File "basicRAT_server.py", line 238, in <module>
    main()
  File "basicRAT_server.py", line 226, in main
    client.send(prompt, cmd, action)
  File "basicRAT_server.py", line 121, in send
    print crypto.AES_decrypt(recv_data, self.dh_key).rstrip()
  File "/Users/bforbes/git/basicRAT/core/crypto.py", line 70, in AES_decrypt
    return unpkcs7(plaintext)
  File "/Users/bforbes/git/basicRAT/core/crypto.py", line 37, in unpkcs7
    raise PaddingError("PKCS7 improper padding {}".format(repr(s[-32:])))
core.crypto.PaddingError: PKCS7 improper padding 'empty:/usr/bin/false\n_webauthser'

**Comment by reznok** [comment]
This appears to be fixed with your send/receive changes

**Comment by vesche** [comment]
Awesome, I'll do some more testing when I get a change. Going to close this for now.
